### ISSUE TITLE
Victory/Defeat determined incorrectly

### ISSUE THREAD

**Issue by captain-majid** [icza/screp#32]
[! 1st win vs UDAI.zip](https://github.com/icza/screp/files/9713146/1st.win.vs.UDAI.zip)

This^ is a very basic replay 1v1 humans, I don't know how screp decided that I'm defeated in this match, I know how complex the algorithm for calculating this is and that no way to be 100% accurate about the victory programmatically. Can you add some notes in place in repmastered.app that victory condition isn't guaranteed to be correct or why it's correct, and maybe some notes how victory is determined in screp (just like Reason element in json file under Computed/LeaveGameCmds) ?

I guess leaving everything thing as is while knowing for sure that there are errors will not please the users, some reasons/hints will be nice.

**Comment by icza** [comment]
Winners are calculated using the "largest remaining team wins" principle. The principle is simple, the implementation is complex. If you are interested in the details, check https://github.com/icza/screp/blob/master/rep/replay.go. Mainly the `computeWinners()` function, but it already uses teams, and team detection is even more complex, relies on data saved in replay, and also `computeMeleeTeams()` and `computeUMSTeams()` functions, and also `Replay.Compute()` method (so basically the whole `replay.go` file).

This is noted on the FAQ page: https://repmastered.app/faq

The reason why `screp` determines you lost is because you saved the replay, and there are no Leave game commands recorded, and there are never leave game commands for the replay saver.

**Comment by captain-majid** [comment]
Nice efforts indeed, but if its me I'd put the infos in the user's hand, and let him decide the winner instead of me making errors/assumptions, I didn't see the FAQs b4, but in addition to FAQs it would be better if a small "info" icon appears "in-place" where the victory/defeat determined, which can also can refer to the same FAQ.

**Comment by icza** [comment]
That includes too many places: every row in the table of the Games page, the Players row in the Game details and Players tab. Implicitly the info is used in every stats displayed.

The info is there, and you do with the info whatever you want to. I agree this may not be completely obvious, I just don't know what would be the best way to make this more known in a pleasant way.

**Comment by captain-majid** [comment]
I agree with what you say, thanks.
