### ISSUE TITLE
Why Land cmd isn't there ?

### ISSUE THREAD

**Issue by captain-majid** [icza/screp#35]
I've noticed that **Lift Off** is always there, but no reference to any Land command for Terran's buildings ! how is this possible ?

**Comment by icza** [comment]
The reason why there is no "Land" command in the list is because "Land" commands are recorded as "Build" commands (have the same command type ID. So just by looking at the command, they can't be distinguished.

What the command actually means depends on the selected unit: if an SCV is selected, it is truly a build command. If a flying building is selected, then it is a "Land" command.

**Comment by icza** [comment]
Fixed in the new v1.8.2 release.
