### ISSUE TITLE
Duplicate actions

### ISSUE THREAD

**Issue by noroot** [icza/screp#5]
Hi, thanks you for project

My question is about duplicated actions, is there any way to avoid it ? 
JSON example attached with twice morphed Overlord 

Example: 
```     {
        "Frame": 1286,
        "PlayerID": 1,
        "Type": {
          "Name": "Unit Morph",
          "ID": 35
        },
        "Unit": {
          "Name": "Overlord",
          "ID": 42
        }
      },
      {
        "Frame": 1288,
        "PlayerID": 1,
        "Type": {
          "Name": "Unit Morph",
          "ID": 35
        },
        "Unit": {
          "Name": "Overlord",
          "ID": 42
        }
      },
```
[who.json.zip](https://github.com/icza/screp/files/1347189/who.json.zip)

Don't know a lot about broodwar replay format, just want to guide , if there is now way to avoid duplicates then how BWcharts work with them. 

thank you again.

**Comment by icza** [comment]
Not really. You see 2 of the Overlord morth command because there are 2 recorded in the replay. And there are 2 recorded in the replay because the player issued 2 of those.

There is no easy way to tell how many of the issued commands get carried out. That requires (simulating) the SC game engine. It may be the user really did build 2 Overlords, it may be only one or none if he/she had not enough minerals.

I think other tools like BWChart don't deal with this, they just display 2 Overlords. There's really nothing more you can do. You can issue a Probe to go and build a Pylon far away. There is no (easy) way to tell if the Probe got to the destination and the player had enough minerals to actually build the Pylon.
